version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: devops_project
      MYSQL_PASSWORD: asdf1234

    ports:
      - "3306:3306"
    networks:
    - app1
  appointments:
    image: abwqr/appointments:f73946
    ports:
      - 9000:9000
    networks:
    - app1
  doctors:
    image: abwqr/doctors:c5caba
    ports:
      - 9090:9090
    networks:
    - app1
  frontend:
    image: abwqr/frontend:fdb39f
    ports:
      - 8080:8080
    networks:
    - app1

networks:
  app1: {}
