version: '3'
services:
  appointments:
    image: abwqr/appointments:f73946
    ports:
      - 9000:9000
    networks:
    - app1
  doctors:
    image: abwqr/doctors:c5caba
    ports:
      - 9090:9090
    networks:
    - app1
  frontend:
    image: abwqr/frontend:e24a4b
    ports:
      - 8080:8080
    networks:
    - app1

networks:
  app1: {}
