version: '3'
services:
  appointments:
    image: abwqr/appointments:8187ca
    ports:
      - 9000:9000
    networks:
    - app1
  doctors:
    image: abwqr/doctors:8fd927
    ports:
      - 9090:9090
    networks:
    - app1
  frontend:
    image: abwqr/frontend:${FRONTEND_VERSION}
    ports:
      - 8080:8080
    networks:
    - app1

networks:
  app1: {}
