name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env: 
        DOCKER_USER:  ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - name: Set env
      run: echo "APPOINTMENTS_VERSION=$(echo $GITHUB_SHA | cut -c 1-6)" >> .env
    - name: Build the Docker image
      run: docker build . --file appointments/Dockerfile --tag abwqr/appointments:$APPOINTMENTS_VERSION
    - name: Docker push
      run: docker push abwqr/appointments:$APPOINTMENTS_VERSION
    - name: Update docker-compose.yml
      run: |
        sed -i "s|image: abwqr/appointments:.*|image: abwqr/appointments:${APPOINTMENTS_VERSION}|g" docker-compose.yml
