name: Frontend Docker Image CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env: 
        DOCKER_USER:  ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - name: Set env
      run: echo "FRONTEND_VERSION=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file frontend/Dockerfile --tag abwqr/frontend:$FRONTEND_VERSION
    - name: Docker push
      run: docker push abwqr/frontend:$FRONTEND_VERSION
    - name: Update docker-compose.yml
      run: |
        sed -i "s|image: abwqr/doctors:.*|image: abwqr/doctors:${FRONTEND_VERSION}|g" docker-compose.yml
    - name: Commit and Push Changes
      run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "Update Docker Compose image tag [skip ci]"
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
